using System.Text;
using System.Text.Json;
using Microsoft.Extensions.Options;
using RabbitMQ.Client;
using RabbitMQ.Client.Events;
 
namespace SubmissionProcessor.Worker;
 
public class SubmissionProcessingWorker : BackgroundService
{
    private readonly IServiceScopeFactory _scopeFactory;
    private readonly RabbitMqOptions _options;
    private readonly ILogger<SubmissionProcessingWorker> _logger;
    private IConnection? _connection;
    private IChannel? _channel;
 
    public SubmissionProcessingWorker(
        IServiceScopeFactory scopeFactory,
        IOptions<RabbitMqOptions> options,
        ILogger<SubmissionProcessingWorker> logger
    )
    {
        _scopeFactory = scopeFactory;
        _options = options.Value;
        _logger = logger;
    }
 
    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        var factory = new ConnectionFactory
        {
            HostName = _options.Host,
            Port = _options.Port,
            UserName = _options.Username,
            Password = _options.Password
        };
    
        _connection = await factory.CreateConnectionAsync();
 
        _channel = await _connection.CreateChannelAsync();            
 
        string dlxExchange = "orders.dlx";
        string dlqName = $"{_options.QueueName}.failed";
        
        // Setup Dead Letter Exchange infrastructure
        await _channel.ExchangeDeclareAsync(
            dlxExchange,   
            ExchangeType.Direct, 
            durable: true           
        );
        await _channel.QueueDeclareAsync(
            dlqName, 
            durable: true, 
            exclusive: false, 
            autoDelete: false  
        );
        await _channel.QueueBindAsync(
            dlqName, 
            dlxExchange,  
            routingKey: _options.QueueName
        );

        // Declare Main Quorum Queue containing the maximum retry delivery boundary
        var queueArguments = new Dictionary<string, object?>
        {
            { "x-queue-type", "quorum" },
            { "x-delivery-limit", 2 }, 
            { "x-dead-letter-exchange", dlxExchange },
            { "x-dead-letter-routing-key", _options.QueueName }
        };


        await _channel.QueueDeclareAsync(
            queue: _options.QueueName,
            durable: true,
            exclusive: false,
            autoDelete: false,
            arguments: queueArguments
        );
 
        await _channel.BasicQosAsync(
            prefetchSize: 0,
            prefetchCount: 1,
            global: false
        );
 
        var consumer = new AsyncEventingBasicConsumer(_channel);
 
        consumer.ReceivedAsync += async (sender, eventArgs) =>
        {
            int deliveryCount = 0;
            Guid CorrelationId = default;

            using var scope = _scopeFactory.CreateScope();
 
            var processingService = scope.ServiceProvider.GetRequiredService<ISubmissionProcessingService>();
            
            try
            {
                var json = Encoding.UTF8.GetString(eventArgs.Body.ToArray());

                _logger.LogInformation("Received message: {Message}", json);
 
                var message = JsonSerializer.Deserialize<SubmissionProcessingRequested>(json);

                if (message == null)
                {
                    _logger.LogWarning(
                        "Unable to deserialize message. CorrelationId: {CorrelationId}, SubmissionId: {SubmisssionId}, FileId: {FileId}",
                        message.CorrelationId,
                        message.SubmissionId,
                        message.FileId
                    );

                    await _channel.BasicNackAsync(
                        eventArgs.DeliveryTag,
                        multiple: false,
                        requeue: false
                    );
 
                    return;
                }

                _logger.LogInformation(
                    "Processing request recieved. CorrelationId: {CorrelationId}, MessageId: {MessageId}, SubmissionId: {SubmisssionId}, FileId: {FileId}",
                    message.CorrelationId,
                    message.MessageId,
                    message.SubmissionId,
                    message.FileId
                );

                CorrelationId = message.CorrelationId;

                // Extract the native x-delivery-count tracking value generated by the Quorum Queue
                if (eventArgs.BasicProperties.Headers?.TryGetValue("x-delivery-count", out var countObj) == true)
                {
                    deliveryCount = Convert.ToInt32(countObj); // Converts 0-indexed count to tracking iteration
                    _logger.LogInformation(
                        "Delivery Count: {Delivery Count}, CorrelationId: {CorrelationId}",
                        deliveryCount,
                        CorrelationId
                    );
                }
 
                await processingService.ProcessAsync(message);
                
                await processingService.UpdateProcessingJob(CorrelationId, "Completed", deliveryCount+1);

                await _channel.BasicAckAsync(
                    eventArgs.DeliveryTag,
                    multiple: false
                );
 
                _logger.LogInformation(
                    "Processing Completed. CorrelationId: {CorrelationId}, Total Attempts: {Attempt}/3, MessageId: {MessageId}, SubmissionId: {SubmisssionId}, FileId: {FileId}",
                    CorrelationId,
                    deliveryCount,
                    message.MessageId,
                    message.SubmissionId,
                    message.FileId
                );

            }
            catch (Exception ex)
            {
                try
                {
                    await processingService.UpdateProcessingJob(CorrelationId, "erorr", deliveryCount+1);
                }
                catch (Exception dbEx)
                {
                    _logger.LogInformation(
                        "Processing Failed to persist job failure state to database. ex: {ex}, CorrelationId: {CorrelationId}",
                        dbEx,
                        CorrelationId
                    );
                }

                await HandleConsumerFailureAsync(eventArgs, ex, CorrelationId, deliveryCount);
            }
        };
 
        await _channel.BasicConsumeAsync(
            queue: _options.QueueName,
            autoAck: false,
            consumer: consumer
        );
 
        _logger.LogInformation("SubmissionProcessingWorker started.");
 
        await Task.Delay(Timeout.Infinite);
    }

    private async Task HandleConsumerFailureAsync(BasicDeliverEventArgs ea, Exception ex, Guid correlationId, int deliveryCount)
    {
        bool isTransient = ex switch
        {
            TransientException => true,
            TimeoutException => true,
            HttpRequestException => true,
            HttpStatusException => true,
            _ => false 
        };

        bool limitExceeded = deliveryCount >= 2;

        _logger.LogError(ex, 
            "Processing faulted. correlationId: {correlationId} | Retry Attempt: {Attempt}/3 | ErrorClass: {ErrClass} | Transient: {IsTransient}", 
            correlationId, deliveryCount, ex.GetType().Name, isTransient);

        if (!isTransient)
        {
            _logger.LogWarning("Permanent error hit for correlationId {correlationId}. Pushing to DLQ.", correlationId);
            await _channel!.BasicNackAsync(ea.DeliveryTag, multiple: false, requeue: false); // Routes to DLQ
        }
        else if (limitExceeded)
        {
            _logger.LogError("Retry threshold broken for transient error on message with correlationId:  {correlationId}. Routing to DLQ.", correlationId);
        }
        else
        {
            _logger.LogInformation("Transient failure on message with correlationId: {correlationId}. Requeueing.", correlationId);
            await _channel!.BasicRejectAsync(ea.DeliveryTag, requeue: true);
        }
    }

    public override async Task StopAsync(CancellationToken cancellationToken)
    {
        _logger.LogInformation("Stopping SubmissionProcessingWorker");
 
        if (_channel is not null)
        {
            await _channel.CloseAsync(cancellationToken);
            await _channel.DisposeAsync();
        }
 
        if (_connection is not null)
        {
            await _connection.CloseAsync(cancellationToken);
            await _connection.DisposeAsync();
        }
 
        await base.StopAsync(cancellationToken);
    }
}